"""add_created_at_to_group

Revision ID: 6ede661b74cd
Revises: 079b3e75e096
Create Date: 2026-05-21 13:52:17.604330

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ede661b74cd"
down_revision: Union[str, Sequence[str], None] = "079b3e75e096"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("created_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "created_at")
    # ### end Alembic commands ###
